### PR TITLE
fix: doesn't do anything if `?` pressed

### PR DESCRIPTION
**Pull request by vhashimotoo**
This should fix when typing `?` in the app search field focuses the search box.

/cc @BinaryMuse

### CODE REVIEW

**Comment by BinaryMuse** [comment]
The issue in https://github.com/electron/electronjs.org/pull/2088 also manifests when typing `/` into the app search box, so I'm not sure this change will be fully sufficient.

**Comment by vhashimotoo** [comment]
Updated fix: If we on `input` element we skip all events, if not we accept all events.

**Comment by vhashimotoo** [comment]
@BinaryMuse can you please merge, I'm don't have permissions.

**Comment by BinaryMuse** [comment]
@HashimotoYT 👍 Currently at summit; will get this merged and release when I get a few minutes.

**Comment by BinaryMuse** [comment]
@HashimotoYT This is published in `v2.0.0`

**Pull request merged**
